# Generated by Django 3.0.6 on 2020-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_type', models.CharField(max_length=255)),
                ('gname', models.CharField(max_length=255)),
                ('descr', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pic_path', models.CharField(default='/static/pdf/contract.pdf', max_length=100)),
                ('brand', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('discount', models.IntegerField(default=1)),
                ('color', models.CharField(max_length=30)),
                ('tag', models.TextField(max_length=2000)),
                ('store', models.IntegerField()),
                ('num', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'GOODS',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('typename', models.CharField(max_length=20)),
                ('type_leave', models.IntegerField()),
                ('popular', models.IntegerField()),
                ('path', models.CharField(max_length=20)),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('nowtime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('browsed_good', models.CharField(max_length=300)),
                ('last_time_buy', models.DateField()),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('login_out', models.DateTimeField()),
                ('buy_sum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
