# Generated by Django 3.0.6 on 2020-05-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table=None,
        ),
    ]
