# Generated by Django 3.0.6 on 2020-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200515_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='popular',
            field=models.IntegerField(default=0),
        ),
    ]
