# Generated by Django 3.0.6 on 2020-05-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200516_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='type_id',
            new_name='paren_id',
        ),
    ]
