# Generated by Django 3.0.6 on 2020-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200517_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='type_leave',
            new_name='type_level',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
