# Generated by Django 3.0.6 on 2020-05-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200517_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='type_level',
            new_name='type',
        ),
    ]
