# Generated by Django 3.0.6 on 2020-05-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200517_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='type',
            new_name='type_level',
        ),
    ]
