# Generated by Django 3.0.6 on 2020-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.CharField(default='/static/shop/images/header/default.jpg', max_length=100),
        ),
    ]
