# Generated by Django 3.0.6 on 2020-06-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200527_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goodsId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraction',
            name='buy_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
